# Generated by Django 2.1.7 on 2019-03-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('availability', models.BooleanField(default=False)),
                ('priceFrom', models.DecimalField(decimal_places=2, max_digits=6)),
                ('priceTo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('place', models.TextField()),
            ],
            options={
                'db_table': 'service',
            },
        ),
    ]
